# Generated by Django 3.1.6 on 2021-03-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_posted']},
        ),
    ]
